const money = (n=0) => new Intl.NumberFormat('ko-KR').format(Math.round(Number(n)||0)) + '원';
const clamp = (n,min,max) => Math.max(min,Math.min(max,n));

function calcNetEstate({assets=0, debts=0, funeral=0, priorGifts=0, deductions=0}={}){
  return {
    gross: Number(assets)||0,
    deductionsBeforeTax: (Number(debts)||0)+(Number(funeral)||0),
    priorGifts: Number(priorGifts)||0,
    deductions: Number(deductions)||0,
    taxableBase: Math.max(0,(Number(assets)||0)-(Number(debts)||0)-(Number(funeral)||0)+(Number(priorGifts)||0)-(Number(deductions)||0))
  };
}

function progressiveInheritanceTax(base=0){
  base = Math.max(0,Number(base)||0);
  if(base<=100_000_000) return base*0.10;
  if(base<=500_000_000) return base*0.20-10_000_000;
  if(base<=1_000_000_000) return base*0.30-60_000_000;
  if(base<=3_000_000_000) return base*0.40-160_000_000;
  return base*0.50-460_000_000;
}

function decisionAssessment({assets=0,debts=0,unknownDebt=false,daysLeft=90}={}){
  assets=Number(assets)||0; debts=Number(debts)||0; daysLeft=Number(daysLeft)||0;
  let level='standard', label='일반 검토', routes=['단순승인'];
  if(unknownDebt || debts>assets*0.7){ level='review'; label='추가 확인 필요'; routes=['한정승인','상속포기','전문가 검토']; }
  if(debts>assets || daysLeft<=14){ level='expert'; label='전문가 우선 검토'; routes=['한정승인','상속포기','전문가 상담']; }
  return {level,label,routes,net:assets-debts,warning: debts>assets ? '현재 입력 기준 채무가 재산을 초과합니다.' : unknownDebt ? '확인되지 않은 채무 가능성이 있어 추가 조회가 필요합니다.' : '현재 입력 기준 채무초과 징후는 확인되지 않았습니다.'};
}

function caseProgress(c){
  const checks = [
    !!c?.decedent?.name,
    (c?.heirs||[]).length>0,
    (c?.assets||[]).length>0,
    !!c?.decision?.selected,
    (c?.documents||[]).some(d=>d.status==='ready'),
    !!c?.registry?.status,
    !!c?.tax?.status,
    !!c?.completion
  ];
  return Math.round(checks.filter(Boolean).length/checks.length*100);
}


const LOGO='assets/logo/finale-logo.png';
const STORAGE='finaleCaseOS_v5';
const seedCase={
 id:'CASE-F-2026-001', title:'김영희님의 상속 Case', createdAt:'2026-09-18',
 decedent:{name:'김영희',death:'2026-03-12',lastAddress:'서울특별시 강남구 테헤란로 123',relation:'자녀',will:'없음'},
 heirs:[{id:1,name:'이강수',relation:'배우자',status:'verified'},{id:2,name:'김지훈',relation:'자녀',status:'verified'},{id:3,name:'김민지',relation:'자녀',status:'need'}],
 assets:[
  {id:1,type:'부동산',name:'서울 ○○아파트',value:500000000,debt:80000000,status:'verified'},
  {id:2,type:'금융',name:'국민은행 예금',value:82000000,debt:0,status:'verified'},
  {id:3,type:'금융',name:'삼성증권 계좌',value:38000000,debt:0,status:'verified'},
  {id:4,type:'보험',name:'삼성생명 보험금',value:22000000,debt:0,status:'review'}
 ],
 govt:{oneStop:'connected-demo',family:'verified-demo',registry:'ready-demo'},
 decision:{selected:'',unknownDebt:false},
 documents:[
  {id:'family',name:'가족관계 확인자료',status:'ready'},
  {id:'split',name:'상속재산분할협의서',status:'draft'},
  {id:'registry',name:'소유권이전등기 신청자료',status:'draft'},
  {id:'tax',name:'상속세 신고자료',status:'draft'}
 ],
 registry:{status:'준비 중',propertyId:1,acquisitionTax:0,steps:['등기정보 확인']},
 tax:{status:'계산 전',funeral:5000000,priorGifts:0,deductions:500000000,filing:'not-started'},
 chats:[], completion:false
};
const defaultState={activeCaseId:seedCase.id,cases:[seedCase],ui:{lastRoute:'home'},aiHistory:[{role:'assistant',text:'안녕하세요. Finale Guide입니다. 상속 절차, 준비서류, 현재 Case 진행상황을 무료로 안내해드릴게요.'}]};
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');return x&&x.cases?x:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function activeCase(){return state.cases.find(c=>c.id===state.activeCaseId)||state.cases[0]}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[m]))}
function toast(msg){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${escapeHtml(msg)}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),2200)}
function route(){return location.hash.slice(1)||state.ui.lastRoute||'home'}
function go(p){location.hash=p}
window.go=go;

const nav=[['home','홈','⌂'],['cases','내 Case','▣'],['assets','재산','⌂'],['tax','세무','₩'],['experts','전문가','◉']];
function layout(body,page='home'){
 const c=activeCase();
 return `<div class="app"><header class="topbar"><div class="brand" onclick="go('home')"><img src="${LOGO}" alt="Finale 로고"><span>Finale</span><small class="desktop-only">Inheritance Case OS</small></div><nav class="nav">${nav.map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')">${n[1]}</button>`).join('')}</nav><div class="top-actions"><button class="ghost desktop-only" onclick="go('ai')">Finale Guide</button><button class="secondary" onclick="go('progress')">${caseProgress(c)}% 진행</button></div></header><main class="shell">${body}</main><nav class="bottom">${nav.map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')"><b>${n[2]}</b><br>${n[1]}</button>`).join('')}</nav><footer class="footer">Finale 데모 · 정부기관/전자신고/결제/전문가 연결은 현재 Mock 연동입니다. 실제 서비스 시 공식 연계 및 자격사 검토가 필요합니다.</footer></div>`
}

function home(){const c=activeCase(),p=caseProgress(c);return layout(`
<section class="hero"><div class="hero-copy"><span class="eyebrow">INHERITANCE CASE OS</span><div class="hero-logo"><img src="${LOGO}" alt="Finale"><strong>Finale</strong></div><h1>복잡한 상속 절차를,<br>하나의 Case로 이어갑니다.</h1><p>상속인 확인부터 재산·채무, 등기, 상속세, 전문가 상담까지<br>같은 사건정보를 사용해 끊기지 않게 관리합니다.</p><div class="row"><button class="primary" onclick="go('cases')">내 Case 이어서 하기 →</button><button class="ghost" onclick="go('case-create')">새 Case 만들기</button></div></div><div class="hero-art"><div class="river"></div><div class="floating-cards"><div class="float-card"><b>상속인 확인</b><span class="tick">✓</span></div><div class="float-card"><b>재산 정리</b><span class="tick">✓</span></div><div class="float-card"><b>법무·세무</b><span class="tick">✓</span></div><div class="float-card"><b>자산 이전</b><span class="tick">✓</span></div></div></div></section>
<div class="quick">${[
 ['cases','▣','내 Case',`${c.title} · ${p}% 진행`],['heirs','♙','상속인','가족관계 확인 및 상속인 후보'],['assets','⌂','재산·채무','안심상속 결과를 한 곳에서'],['experts','◉','전문가','무료 Guide + 유료 전문가 채팅']
].map(x=>`<article class="qcard" onclick="go('${x[0]}')"><div class="ico">${x[1]}</div><b>${x[2]}</b><small>${x[3]}</small></article>`).join('')}</div>
<h2 class="section-title">지금 해야 할 일</h2><div class="grid3"><div class="card"><span class="badge warn">D-29</span><h3>상속재산 추가 확인</h3><p class="muted">보험금 1건의 상속재산 포함 여부를 검토해 주세요.</p><button class="secondary" onclick="go('assets')">확인하기</button></div><div class="card"><span class="badge">오늘</span><h3>가족관계 확인</h3><p class="muted">김민지님의 확인자료가 아직 필요합니다.</p><button class="secondary" onclick="go('heirs')">상속인 관리</button></div><div class="card"><span class="badge">무료</span><h3>Finale Guide</h3><p class="muted">현재 Case를 기준으로 절차와 서류를 안내합니다.</p><button class="secondary" onclick="go('ai')">질문하기</button></div></div>`,'home')}

function cases(){return layout(`<div class="page-head"><div><span class="eyebrow">MY CASE</span><h1>내 상속 Case</h1><p class="muted">중단해도 저장되고, 다시 들어오면 이어서 진행됩니다.</p></div><button class="primary" onclick="go('case-create')">+ 새 Case</button></div><div class="grid2">${state.cases.map(c=>`<article class="card"><div class="row"><span class="badge">진행 중</span><span class="spacer"></span><span class="muted">${escapeHtml(c.id)}</span></div><h2>${escapeHtml(c.title)}</h2><p class="muted">${escapeHtml(c.decedent?.death||'-')} 사망 · 상속인 ${(c.heirs||[]).length}명 · 자산 ${(c.assets||[]).length}건</p><div class="progress"><i style="width:${caseProgress(c)}%"></i></div><div class="row" style="margin-top:16px"><button class="primary" onclick="selectCase('${c.id}')">Case 열기</button><button class="ghost" onclick="duplicateCase('${c.id}')">복제</button></div></article>`).join('')}</div>`,'cases')}
window.selectCase=(id)=>{state.activeCaseId=id;save();go('progress')};
window.duplicateCase=(id)=>{const c=structuredClone(state.cases.find(x=>x.id===id));c.id='CASE-F-'+new Date().getFullYear()+'-'+String(state.cases.length+1).padStart(3,'0');c.title=c.decedent.name+'님의 상속 Case 복사본';state.cases.push(c);save();toast('Case를 복제했습니다.');render()};

function caseCreate(){return layout(`<div class="page-head"><div><span class="eyebrow">NEW CASE</span><h1>새 상속 Case 만들기</h1></div><span class="badge">1 / 5</span></div><div class="grid2"><div class="card"><div class="form"><div class="field"><label>피상속인 이름</label><input id="cc-name" placeholder="예: 김영희"></div><div class="field"><label>사망일</label><input id="cc-death" type="date"></div><div class="field"><label>최후 주소지</label><input id="cc-address" placeholder="주소 입력"></div><div class="field"><label>신청인과의 관계</label><select id="cc-rel"><option>자녀</option><option>배우자</option><option>부모</option><option>형제·자매</option><option>기타</option></select></div><div class="field"><label>유언 존재 여부</label><select id="cc-will"><option>없음</option><option>있음</option><option>확인 중</option></select></div><button class="primary" onclick="createCase()">Case 생성하고 계속 →</button></div></div><div class="card"><h3>Finale가 이어서 하는 일</h3><div class="list">${['상속인 후보 확인','안심상속 결과 통합','채무 위험진단','협의서·등기자료 자동작성','상속세 예상계산','전문가 상담 기록 연결'].map((x,i)=>`<div class="item"><div class="mini">${i+1}</div><div><strong>${x}</strong><small>Case 데이터 재사용</small></div></div>`).join('')}</div></div></div>`,'cases')}
window.createCase=()=>{const name=document.querySelector('#cc-name').value.trim();if(!name)return toast('피상속인 이름을 입력해 주세요.');const id='CASE-F-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-5);const c=structuredClone(seedCase);c.id=id;c.title=`${name}님의 상속 Case`;c.decedent={name,death:document.querySelector('#cc-death').value,lastAddress:document.querySelector('#cc-address').value,relation:document.querySelector('#cc-rel').value,will:document.querySelector('#cc-will').value};c.heirs=[];c.assets=[];c.documents=c.documents.map(d=>({...d,status:'draft'}));c.registry={status:'미시작',steps:[]};c.tax={status:'계산 전',funeral:0,priorGifts:0,deductions:500000000,filing:'not-started'};c.chats=[];c.completion=false;state.cases.unshift(c);state.activeCaseId=id;save();go('heirs')};

function heirs(){const c=activeCase();return layout(`<div class="page-head"><div><span class="eyebrow">HEIRS</span><h1>상속인 확인</h1><p class="muted">공공 연계가 가능한 경우 자동수집하고, 불가능하면 전자증명서/PDF 업로드로 이어갑니다.</p></div><span class="badge">${c.heirs.filter(h=>h.status==='verified').length}/${c.heirs.length||0} 확인</span></div><div class="grid2"><div class="card"><h3>공공정보 연계</h3><div class="list"><div class="item"><div class="mini">G</div><div><strong>가족관계 정보</strong><small>전자증명서/공공 연계 Mock</small></div><span class="spacer"></span><span class="status">연결됨</span></div><div class="item"><div class="mini">✓</div><div><strong>사망정보</strong><small>${escapeHtml(c.decedent.death||'미입력')}</small></div><span class="spacer"></span><span class="status">확인</span></div></div><button class="secondary" style="margin-top:14px" onclick="mockFamilySync()">가족관계 자동조회 DEMO</button></div><div class="card"><h3>확인된 상속인</h3><div class="list">${c.heirs.length?c.heirs.map(h=>`<div class="item"><div class="avatar">${escapeHtml(h.name.slice(0,1))}</div><div><strong>${escapeHtml(h.name)}</strong><small>${escapeHtml(h.relation)}</small></div><span class="spacer"></span><span class="status ${h.status==='verified'?'':'wait'}">${h.status==='verified'?'확인완료':'서류 필요'}</span></div>`).join(''):'<div class="notice">아직 상속인 정보가 없습니다.</div>'}</div><div class="row" style="margin-top:14px"><button class="secondary" onclick="addHeir()">+ 상속인 추가</button><button class="ghost" onclick="toast('PDF 업로드 DEMO: 실제 서비스에서는 전자증명서/PDF 판독으로 대체됩니다.')">가족관계증명서 업로드</button></div></div></div><div class="card" style="margin-top:16px"><h3>상속인 자동판정 결과</h3><p class="muted">현재 등록된 가족관계를 기준으로 상속인 후보를 구성했습니다. 예외 가족관계·유언·인지 등은 전문가 검토 대상으로 분리합니다.</p><div class="notice warn">자동판정은 후보 확인 기능입니다. 복잡한 신분관계 또는 분쟁이 있으면 전문가 검토가 필요합니다.</div></div>`,'cases')}
window.mockFamilySync=()=>{const c=activeCase();if(!c.heirs.length)c.heirs=[{id:Date.now(),name:'배우자(데모)',relation:'배우자',status:'verified'},{id:Date.now()+1,name:'자녀 1(데모)',relation:'자녀',status:'verified'}];else c.heirs=c.heirs.map(h=>({...h,status:'verified'}));save();toast('가족관계 Mock 데이터가 반영되었습니다.');render()};
window.addHeir=()=>modal(`<h2>상속인 추가</h2><div class="form"><div class="field"><label>이름</label><input id="heir-name"></div><div class="field"><label>관계</label><select id="heir-rel"><option>배우자</option><option>자녀</option><option>부모</option><option>형제·자매</option><option>기타</option></select></div><button class="primary" onclick="confirmAddHeir()">추가</button></div>`);
window.confirmAddHeir=()=>{const c=activeCase(),name=document.querySelector('#heir-name').value.trim();if(!name)return;c.heirs.push({id:Date.now(),name,relation:document.querySelector('#heir-rel').value,status:'need'});save();closeModal();render()};

function assets(){const c=activeCase();const total=c.assets.reduce((s,a)=>s+Number(a.value||0),0),debt=c.assets.reduce((s,a)=>s+Number(a.debt||0),0);return layout(`<div class="page-head"><div><span class="eyebrow">ASSETS & DEBTS</span><h1>재산·채무</h1><p class="muted">안심상속 결과와 직접 등록 재산을 하나의 원장으로 관리합니다.</p></div><button class="primary" onclick="mockOneStop()">안심상속 자동조회 DEMO</button></div><div class="grid3"><div class="metric"><small>총 재산</small><b>${money(total)}</b></div><div class="metric"><small>총 확인 채무</small><b>${money(debt)}</b></div><div class="metric"><small>순 재산</small><b style="color:var(--green)">${money(total-debt)}</b></div></div><div class="grid2" style="margin-top:16px"><div class="card"><h3>통합 재산 목록</h3><div class="list">${c.assets.map(a=>`<div class="item"><div class="mini">${a.type==='부동산'?'⌂':a.type==='금융'?'₩':'▦'}</div><div><strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(a.type)} · ${money(a.value)}${a.debt?` · 채무 ${money(a.debt)}`:''}</small></div><span class="spacer"></span><span class="status ${a.status==='review'?'wait':''}">${a.status==='verified'?'확인':'검토'}</span></div>`).join('')||'<div class="notice">재산이 등록되지 않았습니다.</div>'}</div><button class="secondary" style="margin-top:14px" onclick="addAsset()">+ 자산/채무 추가</button></div><div class="card"><h3>외부 조회 상태</h3><div class="list"><div class="item"><div class="mini">G</div><div><strong>안심상속 원스톱</strong><small>금융·토지·자동차·세금·연금</small></div><span class="spacer"></span><span class="status">DEMO 연동</span></div><div class="item"><div class="mini">등</div><div><strong>부동산 등기정보</strong><small>소유권·근저당·압류 확인</small></div><span class="spacer"></span><span class="status">준비</span></div></div><div class="notice" style="margin-top:14px">실서비스에서는 공개 API/기관 연계 가능 범위에 따라 자동수집하고, 미연계 데이터는 전자증명서 또는 업로드로 대체합니다.</div><div class="row" style="margin-top:14px"><button class="secondary" onclick="go('decision')">상속방법 위험진단</button><button class="ghost" onclick="go('registry')">등기 절차</button></div></div></div>`,'assets')}
window.mockOneStop=()=>{const c=activeCase();if(!c.assets.length)c.assets=structuredClone(seedCase.assets);c.govt.oneStop='connected-demo';save();toast('안심상속 Mock 결과를 Case에 반영했습니다.');render()};
window.addAsset=()=>modal(`<h2>자산/채무 추가</h2><div class="form"><div class="field"><label>분류</label><select id="a-type"><option>부동산</option><option>금융</option><option>보험</option><option>자동차</option><option>기타</option></select></div><div class="field"><label>명칭</label><input id="a-name" placeholder="예: 국민은행 예금"></div><div class="field"><label>재산가액</label><input id="a-value" type="number" placeholder="원"></div><div class="field"><label>관련 채무</label><input id="a-debt" type="number" value="0"></div><button class="primary" onclick="confirmAsset()">추가</button></div>`);
window.confirmAsset=()=>{const c=activeCase(),name=document.querySelector('#a-name').value.trim();if(!name)return;c.assets.push({id:Date.now(),type:document.querySelector('#a-type').value,name,value:Number(document.querySelector('#a-value').value||0),debt:Number(document.querySelector('#a-debt').value||0),status:'review'});save();closeModal();render()};

function decision(){const c=activeCase(),a=c.assets.reduce((s,x)=>s+Number(x.value||0),0),d=c.assets.reduce((s,x)=>s+Number(x.debt||0),0);const as=decisionAssessment({assets:a,debts:d,unknownDebt:c.decision.unknownDebt,daysLeft:29});return layout(`<div class="page-head"><div><span class="eyebrow">DECISION ENGINE</span><h1>상속방법 위험진단</h1></div><span class="badge ${as.level==='expert'?'danger':as.level==='review'?'warn':''}">${as.label}</span></div><div class="grid2"><div class="card"><h3>현재 Case 분석</h3><div class="grid3"><div class="metric"><small>재산</small><b>${money(a)}</b></div><div class="metric"><small>채무</small><b>${money(d)}</b></div><div class="metric"><small>차액</small><b>${money(a-d)}</b></div></div><div class="notice ${as.level==='expert'?'danger':as.level==='review'?'warn':''}" style="margin-top:14px">${as.warning}</div><label class="item" style="margin-top:12px"><input type="checkbox" ${c.decision.unknownDebt?'checked':''} onchange="toggleUnknownDebt(this.checked)"><div><strong>아직 확인되지 않은 채무가 있을 수 있음</strong><small>선택 시 보수적으로 위험도를 높입니다.</small></div></label></div><div class="card"><h3>검토 경로</h3><div class="list">${['단순승인','한정승인','상속포기'].map(x=>`<div class="item click" onclick="selectDecision('${x}')"><div class="mini">${x==='단순승인'?'✓':x==='한정승인'?'≦':'×'}</div><div><strong>${x}</strong><small>${x==='단순승인'?'재산과 채무를 함께 승계':x==='한정승인'?'상속재산 범위에서 채무 변제':'상속 효과를 전면적으로 거부'}</small></div><span class="spacer"></span>${c.decision.selected===x?'<span class="status">선택됨</span>':''}</div>`).join('')}</div><div class="notice warn" style="margin-top:14px">Finale는 수치와 위험요소를 비교해 검토 대상을 제시합니다. 개별 사건의 최종 법률판단은 전문가 검토 영역입니다.</div><button class="primary" style="margin-top:14px" onclick="go('experts')">전문가에게 검토 요청</button></div></div>`,'cases')}
window.toggleUnknownDebt=(v)=>{activeCase().decision.unknownDebt=v;save();render()};window.selectDecision=(v)=>{activeCase().decision.selected=v;save();toast(v+'을(를) 선택했습니다.');render()};

function documents(){const c=activeCase();return layout(`<div class="page-head"><div><span class="eyebrow">SMART DOCUMENTS</span><h1>문서 자동작성</h1><p class="muted">한 번 입력한 Case 정보를 여러 문서에 재사용합니다.</p></div><button class="primary" onclick="generateAllDocs()">전체 초안 생성</button></div><div class="grid2"><div class="card"><h3>문서 패키지</h3><div class="list">${c.documents.map(d=>`<div class="item click" onclick="openDocument('${d.id}')"><div class="mini">▤</div><div><strong>${d.name}</strong><small>${d.status==='ready'?'생성 완료':'자동작성 가능'}</small></div><span class="spacer"></span><span class="status ${d.status==='ready'?'':'wait'}">${d.status==='ready'?'준비':'초안'}</span></div>`).join('')}</div></div><div class="card"><h3>작성 원칙</h3><div class="list"><div class="item"><div class="mini">1</div><div><strong>Case 데이터 자동 채움</strong><small>피상속인·상속인·재산정보 반복입력 제거</small></div></div><div class="item"><div class="mini">2</div><div><strong>제출용/검토용 분리</strong><small>자동 초안과 최종 제출요건을 구분</small></div></div><div class="item"><div class="mini">3</div><div><strong>전문가 검토 이력</strong><small>변경사항과 승인자를 기록</small></div></div></div></div></div>`,'cases')}
function docText(id){const c=activeCase();const names=c.heirs.map(h=>`${h.name}(${h.relation})`).join(', ');const assets=c.assets.map(a=>`- ${a.type}: ${a.name} / ${money(a.value)}`).join('\n');if(id==='split')return `상속재산분할협의서 [DEMO 초안]\n\n피상속인: ${c.decedent.name}\n사망일: ${c.decedent.death}\n공동상속인: ${names}\n\n상속재산\n${assets}\n\n※ 실제 협의내용과 등기 제출요건은 최종 확인이 필요합니다.`;if(id==='registry')return `소유권이전등기 신청자료 [DEMO]\n\n등기원인: ${c.decedent.death} 상속\n피상속인: ${c.decedent.name}\n상속인: ${names}\n부동산: ${c.assets.filter(a=>a.type==='부동산').map(a=>a.name).join(', ')||'미등록'}\n\n※ 실제 전자등기 제출은 본인 또는 적법한 자격사의 절차로 진행합니다.`;if(id==='tax')return `상속세 신고자료 요약 [DEMO]\n\n피상속인: ${c.decedent.name}\n총 상속재산: ${money(c.assets.reduce((s,a)=>s+a.value,0))}\n총 확인채무: ${money(c.assets.reduce((s,a)=>s+a.debt,0))}\n\n※ 예상계산자료이며 실제 신고 전 검토가 필요합니다.`;return `가족관계 확인자료 [DEMO]\n피상속인: ${c.decedent.name}\n상속인: ${names}`}
window.openDocument=(id)=>{const c=activeCase();modal(`<h2>${c.documents.find(d=>d.id===id)?.name}</h2><div class="doc-preview" id="doc-text">${escapeHtml(docText(id))}</div><div class="row" style="margin-top:14px"><button class="primary" onclick="downloadDocument('${id}')">파일로 저장</button><button class="secondary" onclick="markDocReady('${id}')">초안 확정</button></div>`)};
window.markDocReady=(id)=>{activeCase().documents.find(d=>d.id===id).status='ready';save();closeModal();render()};window.generateAllDocs=()=>{activeCase().documents.forEach(d=>d.status='ready');save();toast('문서 초안을 모두 생성했습니다.');render()};
window.downloadDocument=(id)=>{const blob=new Blob([docText(id)],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Finale_${id}_${activeCase().id}.txt`;a.click();URL.revokeObjectURL(u)};

function registry(){const c=activeCase(),props=c.assets.filter(a=>a.type==='부동산');return layout(`<div class="page-head"><div><span class="eyebrow">REGISTRY ENGINE</span><h1>부동산 상속등기</h1><p class="muted">등기정보 확인 → 취득세 → 신청자료 → 제출/검토 → 완료 순으로 관리합니다.</p></div><span class="badge">${escapeHtml(c.registry.status)}</span></div><div class="grid2"><div class="card"><h3>부동산</h3><div class="list">${props.map(p=>`<div class="item"><div class="mini">⌂</div><div><strong>${escapeHtml(p.name)}</strong><small>예상가액 ${money(p.value)} · 관련채무 ${money(p.debt)}</small></div><span class="spacer"></span><span class="status">등기정보 확인</span></div>`).join('')||'<div class="notice">부동산이 등록되지 않았습니다.</div>'}</div><button class="secondary" style="margin-top:14px" onclick="mockRegistryLookup()">등기부 자동조회 DEMO</button></div><div class="card"><h3>진행 절차</h3><div class="timeline">${['등기정보 확인','재산분할 확인','취득세 계산','등기 신청자료 생성','본인/법무사 제출','등기완료 확인'].map((x,i)=>`<div class="timeline-row ${i<c.registry.steps.length?'done':i===c.registry.steps.length?'active':''}"><div class="timeline-dot"></div><div><b>${x}</b><small>${i<c.registry.steps.length?'완료':i===c.registry.steps.length?'현재 단계':'대기'}</small></div></div>`).join('')}</div><div class="row"><button class="primary" onclick="advanceRegistry()">다음 단계 처리 DEMO</button><button class="ghost" onclick="go('experts')">법무사 검토</button></div></div></div>`,'cases')}
window.mockRegistryLookup=()=>{const c=activeCase();c.registry.steps=['등기정보 확인'];c.registry.status='진행 중';save();toast('등기정보 Mock 결과를 반영했습니다.');render()};window.advanceRegistry=()=>{const c=activeCase(),steps=['등기정보 확인','재산분할 확인','취득세 계산','등기 신청자료 생성','본인/법무사 제출','등기완료 확인'];if(c.registry.steps.length<steps.length)c.registry.steps.push(steps[c.registry.steps.length]);c.registry.status=c.registry.steps.length===steps.length?'등기 이전 완료':'진행 중';if(c.registry.steps.length===steps.length)c.documents.find(d=>d.id==='registry').status='ready';save();render()};

function tax(){const c=activeCase();const total=c.assets.reduce((s,a)=>s+Number(a.value||0),0),debts=c.assets.reduce((s,a)=>s+Number(a.debt||0),0),cal=calcNetEstate({assets:total,debts,funeral:c.tax.funeral,priorGifts:c.tax.priorGifts,deductions:c.tax.deductions}),tax=progressiveInheritanceTax(cal.taxableBase);return layout(`<div class="page-head"><div><span class="eyebrow">TAX ENGINE</span><h1>상속세 예상계산</h1><p class="muted">Case의 재산·채무 데이터를 자동으로 불러와 예상세액을 계산합니다.</p></div><span class="badge">예상 계산</span></div><div class="grid2"><div class="card"><h3>자동 반영 데이터</h3><div class="table-wrap"><table class="table"><tr><th>항목</th><th>금액</th></tr><tr><td>총 상속재산</td><td class="money">${money(total)}</td></tr><tr><td>확인 채무</td><td class="money">-${money(debts)}</td></tr><tr><td>장례비 등 입력</td><td><input id="t-funeral" type="number" value="${c.tax.funeral}" onchange="updateTaxInput()"></td></tr><tr><td>사전증여 합산 입력</td><td><input id="t-gifts" type="number" value="${c.tax.priorGifts}" onchange="updateTaxInput()"></td></tr><tr><td>공제 입력값</td><td><input id="t-deduction" type="number" value="${c.tax.deductions}" onchange="updateTaxInput()"></td></tr></table></div><div class="notice warn" style="margin-top:12px">재산평가, 배우자공제, 사전증여, 각종 공제는 사건별 요건이 달라 실제 신고 전 검토가 필요합니다.</div></div><div class="card"><h3>예상 결과</h3><div class="metric"><small>예상 과세표준</small><b>${money(cal.taxableBase)}</b></div><div class="metric" style="margin-top:10px"><small>예상 산출세액</small><b style="color:var(--green)">${money(tax)}</b></div><div class="list" style="margin-top:14px"><div class="item"><div class="mini">1</div><div><strong>신고자료 자동구성</strong><small>재산명세·채무·공제 입력값 재사용</small></div></div><div class="item"><div class="mini">2</div><div><strong>직접신고 / 세무사 검토</strong><small>최종 제출 경로를 분리</small></div></div><div class="item"><div class="mini">3</div><div><strong>납부 연결</strong><small>세금과 플랫폼/전문가 비용을 분리</small></div></div></div><div class="row" style="margin-top:14px"><button class="primary" onclick="prepareTaxFiling()">신고자료 생성</button><button class="ghost" onclick="go('experts')">세무사 상담</button></div></div></div>`,'tax')}
window.updateTaxInput=()=>{const c=activeCase();c.tax.funeral=Number(document.querySelector('#t-funeral').value||0);c.tax.priorGifts=Number(document.querySelector('#t-gifts').value||0);c.tax.deductions=Number(document.querySelector('#t-deduction').value||0);save();render()};window.prepareTaxFiling=()=>{const c=activeCase();c.tax.status='신고자료 준비';c.tax.filing='draft-ready';c.documents.find(d=>d.id==='tax').status='ready';save();toast('상속세 신고자료 초안을 생성했습니다.');render()};

const experts=[
 {id:'tax1',type:'세무사',name:'김○○ 세무사',desc:'상속세·증여세·재산평가',price:30000,rating:'★ 4.9'},
 {id:'reg1',type:'법무사',name:'박○○ 법무사',desc:'상속등기·한정승인·서류검토',price:25000,rating:'★ 4.8'},
 {id:'law1',type:'변호사',name:'이○○ 변호사',desc:'상속분쟁·유언·복잡사건',price:50000,rating:'★ 4.9'}
];
function expertsPage(){const c=activeCase();const open=c.chats.filter(x=>x.status!=='closed');return layout(`<div class="page-head"><div><span class="eyebrow">FINALE EXPERT</span><h1>전문가 상담</h1><p class="muted">무료 Guide로 기본 안내를 받고, 깊은 판단이 필요할 때 유료 전문가 채팅으로 연결합니다.</p></div><button class="secondary" onclick="go('ai')">무료 Finale Guide</button></div>${open.length?`<div class="card" style="margin-bottom:16px"><h3>진행 중 상담</h3><div class="list">${open.map(s=>`<div class="item click" onclick="openChat('${s.id}')"><div class="avatar">${s.expert.type.slice(0,1)}</div><div><strong>${s.expert.name}</strong><small>${s.status==='waiting-expert'?'전문가 답변 대기':'상담 진행 중'} · 뒤로가도 대화 유지</small></div><span class="spacer"></span><span class="status">상담 중</span></div>`).join('')}</div></div>`:''}<div class="grid2"><div class="card"><h3>전문가 선택</h3><div class="list">${experts.map(e=>`<div class="expert-card"><div class="avatar">${e.type.slice(0,1)}</div><div><strong>${e.name}</strong><p>${e.desc}</p><span class="rating">${e.rating}</span></div><div><div class="price">${money(e.price)}</div><button class="primary" onclick="startPaidChat('${e.id}')">채팅 상담</button></div></div>`).join('')}</div></div><div class="card"><h3>결제 구조</h3><div class="notice">AI 기본 안내는 무료입니다. 전문가 채팅은 상담료를 결제한 뒤 사건 기반 상담방이 생성됩니다. 실제 서비스에서는 전문가 비용과 Finale 플랫폼 비용을 분리하도록 설계합니다.</div><div class="list" style="margin-top:14px"><div class="item"><div class="mini">✓</div><div><strong>대화 영구 유지</strong><small>앱 종료·뒤로가기 후에도 동일 상담방 복귀</small></div></div><div class="item"><div class="mini">✓</div><div><strong>Case 자료 공유</strong><small>상속인·재산·세무·등기 진행상황을 같은 Case에서 확인</small></div></div><div class="item"><div class="mini">✓</div><div><strong>상담 종료 버튼</strong><small>종료 전까지 상담 상태 유지</small></div></div></div></div></div>`,'experts')}
function startPaidChat(id){const e=experts.find(x=>x.id===id);modal(`<h2>${e.name} 채팅상담</h2><p class="muted">${e.desc}</p><div class="metric"><small>상담료</small><b>${money(e.price)}</b></div><div class="notice" style="margin-top:12px">DEMO 결제입니다. 실제 결제는 PG 연동 후 상담방을 생성하도록 구성합니다.</div><button class="primary" style="width:100%;margin-top:16px" onclick="payAndOpen('${id}')">DEMO 결제하고 상담 시작</button>`)}
window.startPaidChat=startPaidChat;
window.payAndOpen=(id)=>{const e=experts.find(x=>x.id===id),c=activeCase();const existing=c.chats.find(s=>s.expert.id===id&&s.status!=='closed');if(existing){closeModal();return openChat(existing.id)}const s={id:'CHAT-'+Date.now(),expert:e,status:'open',paid:true,createdAt:new Date().toISOString(),messages:[{role:'system',text:'상담이 시작되었습니다. 뒤로가거나 앱을 종료해도 상담은 유지됩니다.'},{role:'expert',text:`안녕하세요. ${e.name}입니다. 현재 Finale Case 요약을 확인했습니다. 궁금한 내용을 남겨주세요.`}]};c.chats.push(s);save();closeModal();openChat(s.id)};
window.openChat=(id)=>{location.hash='chat/'+id};
function chat(id){const c=activeCase(),s=c.chats.find(x=>x.id===id);if(!s)return layout('<div class="card">상담방을 찾을 수 없습니다.</div>','experts');return layout(`<div class="chat-wrap"><aside class="chat-list"><h3>상담 기록</h3>${c.chats.map(x=>`<div class="item click" onclick="openChat('${x.id}')"><div class="avatar">${x.expert.type.slice(0,1)}</div><div><strong>${x.expert.name}</strong><small>${x.status==='closed'?'상담 종료':'상담 중'}</small></div></div>`).join('')}</aside><section class="chat-room"><div class="chat-head"><button class="ghost" onclick="go('experts')">←</button><div class="avatar">${s.expert.type.slice(0,1)}</div><div><strong>${s.expert.name}</strong><small class="muted">${s.status==='closed'?'상담 종료':'● 상담 진행 중'}</small></div><span class="spacer"></span>${s.status!=='closed'?`<button class="danger-btn" onclick="confirmEndChat('${s.id}')">상담 종료</button>`:''}</div><div class="chat-body" id="chat-body">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':m.role==='expert'?'expert':'system'}">${escapeHtml(m.text)}</div>`).join('')}</div>${s.status!=='closed'?`<div class="chat-compose"><textarea id="chat-input" placeholder="메시지를 입력하세요"></textarea><button class="primary" onclick="sendChat('${s.id}')">전송</button></div>`:`<div class="notice" style="margin:12px">이 상담은 종료되었습니다. 기록은 Case에 계속 보관됩니다.</div>`}</section></div>`,'experts')}
window.sendChat=(id)=>{const c=activeCase(),s=c.chats.find(x=>x.id===id),el=document.querySelector('#chat-input'),text=el.value.trim();if(!text)return;s.messages.push({role:'user',text});s.status='waiting-expert';save();render();setTimeout(()=>{const ss=activeCase().chats.find(x=>x.id===id);if(!ss||ss.status==='closed')return;ss.messages.push({role:'expert',text:'DEMO 답변입니다. 실제 서비스에서는 담당 전문가가 이 상담방에 실시간으로 답변합니다. 필요한 경우 Case 자료에 반영할 항목을 정리해드리겠습니다.'});ss.status='open';save();if(route()===`chat/${id}`)render()},700)};
window.confirmEndChat=(id)=>modal(`<h2>상담을 종료하시겠습니까?</h2><p class="muted">종료 후에도 대화기록은 Case에 보관됩니다.</p><div class="notice">미해결 사항이 있으면 계속 상담을 선택해 주세요.</div><div class="row" style="margin-top:15px"><button class="ghost" onclick="closeModal()">계속 상담</button><button class="danger-btn" onclick="endChat('${id}')">상담 종료</button></div>`);window.endChat=(id)=>{const s=activeCase().chats.find(x=>x.id===id);s.status='closed';s.closedAt=new Date().toISOString();s.messages.push({role:'system',text:'상담이 종료되었습니다. 상담 기록은 Case에 보관됩니다.'});save();closeModal();render()};

function ai(){return layout(`<div class="page-head"><div><span class="eyebrow">FINALE GUIDE</span><h1>무료 AI/자동 안내</h1><p class="muted">현재 데모는 외부 AI API 없이 규칙 기반으로 동작합니다. 나중에 Gemini/OpenAI 등 Provider만 교체할 수 있습니다.</p></div><span class="ai-chip">● API 없이 동작</span></div><div class="chat-room" style="min-height:650px"><div class="chat-head"><img src="${LOGO}" style="width:48px;height:34px;object-fit:contain"><div><strong>Finale Guide</strong><small class="muted">절차·서류·Case 진행상황 무료 안내</small></div></div><div class="chat-body" id="ai-body">${state.aiHistory.map(m=>`<div class="bubble ${m.role==='user'?'user':'expert'}">${escapeHtml(m.text)}</div>`).join('')}</div><div class="chat-compose"><textarea id="ai-input" placeholder="예: 상속세 신고는 어떻게 준비해?"></textarea><button class="primary" onclick="sendAI()">전송</button></div></div>`,'home')}
window.sendAI=()=>{const el=document.querySelector('#ai-input'),q=el.value.trim();if(!q)return;state.aiHistory.push({role:'user',text:q});state.aiHistory.push({role:'assistant',text:guideAnswer(q)});save();render()};
function guideAnswer(q){const c=activeCase(),s=q.toLowerCase();if(s.includes('상속세')||s.includes('세금'))return `현재 ${c.title}에는 재산 ${c.assets.length}건이 등록되어 있습니다. '세무' 메뉴에서 재산·채무가 자동 반영된 예상계산을 확인할 수 있습니다. 재산평가나 사전증여처럼 판단이 필요한 부분은 세무사 상담으로 이어갈 수 있습니다.`;if(s.includes('채무')||s.includes('빚')||s.includes('한정승인')||s.includes('포기'))return `현재 Case의 재산·채무를 비교한 뒤 '상속방법 위험진단'에서 단순승인·한정승인·상속포기 검토 경로를 확인할 수 있습니다. 채무초과나 기한 임박이면 전문가 우선 검토로 표시됩니다.`;if(s.includes('등기')||s.includes('부동산'))return `부동산 상속등기는 등기정보 확인 → 재산분할 → 취득세 → 신청자료 → 제출/검토 → 완료 순으로 관리합니다. '내 Case > 부동산 상속등기'에서 진행할 수 있습니다.`;if(s.includes('서류')||s.includes('협의서'))return `Case에 입력된 피상속인·상속인·재산정보를 이용해 상속재산분할협의서, 등기자료, 상속세 신고자료의 DEMO 초안을 자동 생성할 수 있습니다.`;return `현재 Case 진행률은 ${caseProgress(c)}%입니다. 상속인 확인, 재산·채무, 등기, 상속세, 전문가 상담 중 궁금한 항목을 조금 더 구체적으로 말씀해 주세요.`}

function progress(){const c=activeCase(),p=caseProgress(c);const steps=[['Case 기본정보',!!c.decedent.name,'case-create'],['상속인 확인',c.heirs.length>0,'heirs'],['재산·채무',c.assets.length>0,'assets'],['상속방법',!!c.decision.selected,'decision'],['문서 자동작성',c.documents.some(d=>d.status==='ready'),'documents'],['부동산 등기',c.registry.status==='등기 이전 완료','registry'],['상속세',c.tax.filing==='draft-ready','tax'],['Case 완료',!!c.completion,'progress']];return layout(`<div class="page-head"><div><span class="eyebrow">CASE TIMELINE</span><h1>${escapeHtml(c.title)}</h1><p class="muted">${escapeHtml(c.id)} · ${escapeHtml(c.decedent.death||'-')} 사망</p></div><span class="badge">${p}% 완료</span></div><div class="grid2"><div class="card"><div class="progress"><i style="width:${p}%"></i></div><h3 style="margin-top:18px">전체 진행상황</h3><div class="list">${steps.map(([n,done,r],i)=>`<div class="item click" onclick="go('${r}')"><div class="mini">${done?'✓':i+1}</div><div><strong>${n}</strong><small>${done?'완료/확인됨':'진행 필요'}</small></div><span class="spacer"></span><span class="status ${done?'':'off'}">${done?'완료':'대기'}</span></div>`).join('')}</div></div><div class="card"><h3>자동화 상태</h3><div class="list"><div class="item"><div class="mini">G</div><div><strong>안심상속</strong><small>Mock 연동</small></div><span class="spacer"></span><span class="status">연결</span></div><div class="item"><div class="mini">문</div><div><strong>문서 엔진</strong><small>Case 데이터 자동채움</small></div><span class="spacer"></span><span class="status">사용 가능</span></div><div class="item"><div class="mini">세</div><div><strong>Tax Engine</strong><small>예상세액 자동계산</small></div><span class="spacer"></span><span class="status">사용 가능</span></div><div class="item"><div class="mini">◉</div><div><strong>Expert Chat</strong><small>${c.chats.filter(x=>x.status!=='closed').length}건 진행 중</small></div><span class="spacer"></span><span class="status">활성</span></div></div>${p>=75&&!c.completion?'<button class="primary" style="margin-top:16px" onclick="completeCase()">Case 완료 처리 DEMO</button>':''}${c.completion?'<div class="notice" style="margin-top:16px">이 Case는 완료 처리되었습니다. 모든 기록은 보관됩니다.</div>':''}</div></div>`,'cases')}
window.completeCase=()=>{activeCase().completion=true;save();toast('Case를 완료 처리했습니다.');render()};

function modal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="close" onclick="closeModal()">×</button>${content}</div></div>`)}window.closeModal=()=>document.querySelector('.modal-back')?.remove();

function render(){const r=route();state.ui.lastRoute=r;save();let body;if(r.startsWith('chat/'))body=chat(r.split('/')[1]);else body=({home,cases,'case-create':caseCreate,heirs,assets,decision,documents,registry,tax,experts:expertsPage,ai,progress}[r]||home)();document.querySelector('#app').innerHTML=body;window.scrollTo(0,0);requestAnimationFrame(()=>{const el=document.querySelector('#chat-body,#ai-body');if(el)el.scrollTop=el.scrollHeight})}
addEventListener('hashchange',render);render();
